# Generated by Django 6.0.4 on 2026-05-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
